apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookmate-user
  namespace: cookmate
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%  
  selector:
    matchLabels:
      app: cookmate-user
  template:
    metadata:
      labels:
        app: cookmate-user
    spec:
      containers:
      - name: cookmate-user
        image: kiennlt/cookmate-user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: cookmate-user-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cookmate-user
  namespace: cookmate
spec:
  selector:
    app: cookmate-user
  ports:
    - port: 80
      targetPort: 5001
  type: ClusterIP
